"""Create todos table

Revision ID: 1b34799a40ec
Revises: e6272b6be5aa
Create Date: 2024-04-19 19:09:33.188574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '1b34799a40ec'
down_revision: Union[str, None] = 'e6272b6be5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    insp = Inspector.from_engine(op.get_bind())
    if not insp.has_table('todos'):
        op.create_table(
            'todos',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('title', sa.String(100), nullable=False),
            sa.Column('description', sa.String(250), nullable=False),
            sa.Column('priority', sa.Integer),
            sa.Column('complete', sa.Boolean, nullable=False),
            sa.Column('owner_id', sa.Integer, sa.ForeignKey('users.id')),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
