"""Create users table

Revision ID: e6272b6be5aa
Revises: 
Create Date: 2024-04-19 14:13:44.930710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'e6272b6be5aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    insp = Inspector.from_engine(op.get_bind())
    if not insp.has_table('users'):
        op.create_table(
            'users',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('email', sa.String(100), nullable=False, unique=True),
            sa.Column('username', sa.String(50), nullable=False, unique=True),
            sa.Column('first_name', sa.String(255), nullable=False),
            sa.Column('last_name', sa.String(255), nullable=False),
            sa.Column('hashed_password', sa.String(500), nullable=False),
            sa.Column('is_active', sa.Boolean, nullable=False, default=True),
            sa.Column('role', sa.String(50), nullable=False)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
