version: "3.9"

services:
    web:
        build:
            context: ./api
        volumes:
            - ./api:/app
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASSWORD=changeme
            - DB_PORT=5432
            - DEBUG=1
        depends_on:
            - db
    db:
        image: postgres:16-alpine
        volumes: 
            - dev-db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=changeme

volumes:
    dev-db-data: